#pragma once

#include <cstddef>
#include <cstdint>

namespace plotix {
namespace embedded {

// Embedded SDF font atlas PNG data (512x512, ASCII 32-126)
// Generated by tools/generate_atlas.py from a system sans-serif font.
extern const uint8_t font_atlas_png[];
extern const size_t  font_atlas_png_size;

// Embedded glyph metrics as JSON string
extern const char font_atlas_metrics_json[];

} // namespace embedded
} // namespace plotix
