# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AckStatePayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AckStatePayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAckStatePayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AckStatePayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AckStatePayload
    def Revision(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def AckStatePayloadStart(builder):
    builder.StartObject(1)

def Start(builder):
    AckStatePayloadStart(builder)

def AckStatePayloadAddRevision(builder, revision):
    builder.PrependUint64Slot(0, revision, 0)

def AddRevision(builder, revision):
    AckStatePayloadAddRevision(builder, revision)

def AckStatePayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return AckStatePayloadEnd(builder)
