# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CmdAssignFiguresPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CmdAssignFiguresPayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCmdAssignFiguresPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CmdAssignFiguresPayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CmdAssignFiguresPayload
    def WindowId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # CmdAssignFiguresPayload
    def FigureIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # CmdAssignFiguresPayload
    def FigureIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint64Flags, o)
        return 0

    # CmdAssignFiguresPayload
    def FigureIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CmdAssignFiguresPayload
    def FigureIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # CmdAssignFiguresPayload
    def ActiveFigureId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def CmdAssignFiguresPayloadStart(builder):
    builder.StartObject(3)

def Start(builder):
    CmdAssignFiguresPayloadStart(builder)

def CmdAssignFiguresPayloadAddWindowId(builder, windowId):
    builder.PrependUint64Slot(0, windowId, 0)

def AddWindowId(builder, windowId):
    CmdAssignFiguresPayloadAddWindowId(builder, windowId)

def CmdAssignFiguresPayloadAddFigureIds(builder, figureIds):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(figureIds), 0)

def AddFigureIds(builder, figureIds):
    CmdAssignFiguresPayloadAddFigureIds(builder, figureIds)

def CmdAssignFiguresPayloadStartFigureIdsVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartFigureIdsVector(builder, numElems):
    return CmdAssignFiguresPayloadStartFigureIdsVector(builder, numElems)

def CmdAssignFiguresPayloadAddActiveFigureId(builder, activeFigureId):
    builder.PrependUint64Slot(2, activeFigureId, 0)

def AddActiveFigureId(builder, activeFigureId):
    CmdAssignFiguresPayloadAddActiveFigureId(builder, activeFigureId)

def CmdAssignFiguresPayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return CmdAssignFiguresPayloadEnd(builder)
