# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CmdSetActivePayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CmdSetActivePayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCmdSetActivePayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CmdSetActivePayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CmdSetActivePayload
    def WindowId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # CmdSetActivePayload
    def FigureId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def CmdSetActivePayloadStart(builder):
    builder.StartObject(2)

def Start(builder):
    CmdSetActivePayloadStart(builder)

def CmdSetActivePayloadAddWindowId(builder, windowId):
    builder.PrependUint64Slot(0, windowId, 0)

def AddWindowId(builder, windowId):
    CmdSetActivePayloadAddWindowId(builder, windowId)

def CmdSetActivePayloadAddFigureId(builder, figureId):
    builder.PrependUint64Slot(1, figureId, 0)

def AddFigureId(builder, figureId):
    CmdSetActivePayloadAddFigureId(builder, figureId)

def CmdSetActivePayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return CmdSetActivePayloadEnd(builder)
