# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

class DiffOpType(object):
    SET_AXIS_LIMITS = 1
    SET_SERIES_COLOR = 2
    SET_SERIES_VISIBLE = 3
    SET_FIGURE_TITLE = 4
    SET_GRID_VISIBLE = 5
    SET_LINE_WIDTH = 6
    SET_MARKER_SIZE = 7
    SET_OPACITY = 8
    ADD_FIGURE = 10
    REMOVE_FIGURE = 11
    SET_SERIES_DATA = 12
    SET_AXIS_XLABEL = 13
    SET_AXIS_YLABEL = 14
    SET_AXIS_TITLE = 15
    SET_SERIES_LABEL = 16
    REMOVE_SERIES = 17
    SET_KNOB_VALUE = 20
    SET_AXIS_ZLIMITS = 21
    ADD_SERIES = 22
    ADD_AXES = 23
