# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DiffOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DiffOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDiffOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DiffOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DiffOp
    def OpType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 1

    # DiffOp
    def FigureId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # DiffOp
    def AxesIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # DiffOp
    def SeriesIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # DiffOp
    def F1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # DiffOp
    def F2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # DiffOp
    def F3(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # DiffOp
    def F4(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # DiffOp
    def BoolVal(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # DiffOp
    def StrVal(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DiffOp
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # DiffOp
    def DataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # DiffOp
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DiffOp
    def DataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        return o == 0

def DiffOpStart(builder):
    builder.StartObject(11)

def Start(builder):
    DiffOpStart(builder)

def DiffOpAddOpType(builder, opType):
    builder.PrependUint8Slot(0, opType, 1)

def AddOpType(builder, opType):
    DiffOpAddOpType(builder, opType)

def DiffOpAddFigureId(builder, figureId):
    builder.PrependUint64Slot(1, figureId, 0)

def AddFigureId(builder, figureId):
    DiffOpAddFigureId(builder, figureId)

def DiffOpAddAxesIndex(builder, axesIndex):
    builder.PrependUint32Slot(2, axesIndex, 0)

def AddAxesIndex(builder, axesIndex):
    DiffOpAddAxesIndex(builder, axesIndex)

def DiffOpAddSeriesIndex(builder, seriesIndex):
    builder.PrependUint32Slot(3, seriesIndex, 0)

def AddSeriesIndex(builder, seriesIndex):
    DiffOpAddSeriesIndex(builder, seriesIndex)

def DiffOpAddF1(builder, f1):
    builder.PrependFloat64Slot(4, f1, 0.0)

def AddF1(builder, f1):
    DiffOpAddF1(builder, f1)

def DiffOpAddF2(builder, f2):
    builder.PrependFloat64Slot(5, f2, 0.0)

def AddF2(builder, f2):
    DiffOpAddF2(builder, f2)

def DiffOpAddF3(builder, f3):
    builder.PrependFloat64Slot(6, f3, 0.0)

def AddF3(builder, f3):
    DiffOpAddF3(builder, f3)

def DiffOpAddF4(builder, f4):
    builder.PrependFloat64Slot(7, f4, 0.0)

def AddF4(builder, f4):
    DiffOpAddF4(builder, f4)

def DiffOpAddBoolVal(builder, boolVal):
    builder.PrependBoolSlot(8, boolVal, 0)

def AddBoolVal(builder, boolVal):
    DiffOpAddBoolVal(builder, boolVal)

def DiffOpAddStrVal(builder, strVal):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(strVal), 0)

def AddStrVal(builder, strVal):
    DiffOpAddStrVal(builder, strVal)

def DiffOpAddData(builder, data):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)

def AddData(builder, data):
    DiffOpAddData(builder, data)

def DiffOpStartDataVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartDataVector(builder, numElems):
    return DiffOpStartDataVector(builder, numElems)

def DiffOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return DiffOpEnd(builder)
