# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EvtFigureDestroyedPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EvtFigureDestroyedPayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEvtFigureDestroyedPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EvtFigureDestroyedPayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EvtFigureDestroyedPayload
    def FigureId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # EvtFigureDestroyedPayload
    def Reason(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def EvtFigureDestroyedPayloadStart(builder):
    builder.StartObject(2)

def Start(builder):
    EvtFigureDestroyedPayloadStart(builder)

def EvtFigureDestroyedPayloadAddFigureId(builder, figureId):
    builder.PrependUint64Slot(0, figureId, 0)

def AddFigureId(builder, figureId):
    EvtFigureDestroyedPayloadAddFigureId(builder, figureId)

def EvtFigureDestroyedPayloadAddReason(builder, reason):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(reason), 0)

def AddReason(builder, reason):
    EvtFigureDestroyedPayloadAddReason(builder, reason)

def EvtFigureDestroyedPayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return EvtFigureDestroyedPayloadEnd(builder)
