# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EvtInputPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EvtInputPayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEvtInputPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EvtInputPayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EvtInputPayload
    def WindowId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # EvtInputPayload
    def InputType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 1

    # EvtInputPayload
    def Key(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EvtInputPayload
    def Mods(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EvtInputPayload
    def X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # EvtInputPayload
    def Y(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # EvtInputPayload
    def FigureId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # EvtInputPayload
    def AxesIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def EvtInputPayloadStart(builder):
    builder.StartObject(8)

def Start(builder):
    EvtInputPayloadStart(builder)

def EvtInputPayloadAddWindowId(builder, windowId):
    builder.PrependUint64Slot(0, windowId, 0)

def AddWindowId(builder, windowId):
    EvtInputPayloadAddWindowId(builder, windowId)

def EvtInputPayloadAddInputType(builder, inputType):
    builder.PrependUint8Slot(1, inputType, 1)

def AddInputType(builder, inputType):
    EvtInputPayloadAddInputType(builder, inputType)

def EvtInputPayloadAddKey(builder, key):
    builder.PrependInt32Slot(2, key, 0)

def AddKey(builder, key):
    EvtInputPayloadAddKey(builder, key)

def EvtInputPayloadAddMods(builder, mods):
    builder.PrependInt32Slot(3, mods, 0)

def AddMods(builder, mods):
    EvtInputPayloadAddMods(builder, mods)

def EvtInputPayloadAddX(builder, x):
    builder.PrependFloat64Slot(4, x, 0.0)

def AddX(builder, x):
    EvtInputPayloadAddX(builder, x)

def EvtInputPayloadAddY(builder, y):
    builder.PrependFloat64Slot(5, y, 0.0)

def AddY(builder, y):
    EvtInputPayloadAddY(builder, y)

def EvtInputPayloadAddFigureId(builder, figureId):
    builder.PrependUint64Slot(6, figureId, 0)

def AddFigureId(builder, figureId):
    EvtInputPayloadAddFigureId(builder, figureId)

def EvtInputPayloadAddAxesIndex(builder, axesIndex):
    builder.PrependUint32Slot(7, axesIndex, 0)

def AddAxesIndex(builder, axesIndex):
    EvtInputPayloadAddAxesIndex(builder, axesIndex)

def EvtInputPayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return EvtInputPayloadEnd(builder)
