# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EvtWindowClosedPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EvtWindowClosedPayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEvtWindowClosedPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EvtWindowClosedPayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EvtWindowClosedPayload
    def FigureId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # EvtWindowClosedPayload
    def WindowId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # EvtWindowClosedPayload
    def Reason(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def EvtWindowClosedPayloadStart(builder):
    builder.StartObject(3)

def Start(builder):
    EvtWindowClosedPayloadStart(builder)

def EvtWindowClosedPayloadAddFigureId(builder, figureId):
    builder.PrependUint64Slot(0, figureId, 0)

def AddFigureId(builder, figureId):
    EvtWindowClosedPayloadAddFigureId(builder, figureId)

def EvtWindowClosedPayloadAddWindowId(builder, windowId):
    builder.PrependUint64Slot(1, windowId, 0)

def AddWindowId(builder, windowId):
    EvtWindowClosedPayloadAddWindowId(builder, windowId)

def EvtWindowClosedPayloadAddReason(builder, reason):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(reason), 0)

def AddReason(builder, reason):
    EvtWindowClosedPayloadAddReason(builder, reason)

def EvtWindowClosedPayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return EvtWindowClosedPayloadEnd(builder)
