# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HelloPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HelloPayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHelloPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HelloPayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HelloPayload
    def ProtocolMajor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 1

    # HelloPayload
    def ProtocolMinor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # HelloPayload
    def AgentBuild(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # HelloPayload
    def Capabilities(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # HelloPayload
    def ClientType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def HelloPayloadStart(builder):
    builder.StartObject(5)

def Start(builder):
    HelloPayloadStart(builder)

def HelloPayloadAddProtocolMajor(builder, protocolMajor):
    builder.PrependUint16Slot(0, protocolMajor, 1)

def AddProtocolMajor(builder, protocolMajor):
    HelloPayloadAddProtocolMajor(builder, protocolMajor)

def HelloPayloadAddProtocolMinor(builder, protocolMinor):
    builder.PrependUint16Slot(1, protocolMinor, 0)

def AddProtocolMinor(builder, protocolMinor):
    HelloPayloadAddProtocolMinor(builder, protocolMinor)

def HelloPayloadAddAgentBuild(builder, agentBuild):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(agentBuild), 0)

def AddAgentBuild(builder, agentBuild):
    HelloPayloadAddAgentBuild(builder, agentBuild)

def HelloPayloadAddCapabilities(builder, capabilities):
    builder.PrependUint32Slot(3, capabilities, 0)

def AddCapabilities(builder, capabilities):
    HelloPayloadAddCapabilities(builder, capabilities)

def HelloPayloadAddClientType(builder, clientType):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(clientType), 0)

def AddClientType(builder, clientType):
    HelloPayloadAddClientType(builder, clientType)

def HelloPayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return HelloPayloadEnd(builder)
