# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

class InputType(object):
    KEY_PRESS = 1
    KEY_RELEASE = 2
    MOUSE_BUTTON = 3
    MOUSE_MOVE = 4
    SCROLL = 5
