# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ReqAddSeriesPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReqAddSeriesPayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReqAddSeriesPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ReqAddSeriesPayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ReqAddSeriesPayload
    def FigureId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ReqAddSeriesPayload
    def AxesIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ReqAddSeriesPayload
    def SeriesType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ReqAddSeriesPayload
    def Label(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ReqAddSeriesPayloadStart(builder):
    builder.StartObject(4)

def Start(builder):
    ReqAddSeriesPayloadStart(builder)

def ReqAddSeriesPayloadAddFigureId(builder, figureId):
    builder.PrependUint64Slot(0, figureId, 0)

def AddFigureId(builder, figureId):
    ReqAddSeriesPayloadAddFigureId(builder, figureId)

def ReqAddSeriesPayloadAddAxesIndex(builder, axesIndex):
    builder.PrependUint32Slot(1, axesIndex, 0)

def AddAxesIndex(builder, axesIndex):
    ReqAddSeriesPayloadAddAxesIndex(builder, axesIndex)

def ReqAddSeriesPayloadAddSeriesType(builder, seriesType):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(seriesType), 0)

def AddSeriesType(builder, seriesType):
    ReqAddSeriesPayloadAddSeriesType(builder, seriesType)

def ReqAddSeriesPayloadAddLabel(builder, label):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(label), 0)

def AddLabel(builder, label):
    ReqAddSeriesPayloadAddLabel(builder, label)

def ReqAddSeriesPayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return ReqAddSeriesPayloadEnd(builder)
