# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ReqCreateAxesPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReqCreateAxesPayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReqCreateAxesPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ReqCreateAxesPayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ReqCreateAxesPayload
    def FigureId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ReqCreateAxesPayload
    def GridRows(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 1

    # ReqCreateAxesPayload
    def GridCols(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 1

    # ReqCreateAxesPayload
    def GridIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 1

    # ReqCreateAxesPayload
    def Is3d(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def ReqCreateAxesPayloadStart(builder):
    builder.StartObject(5)

def Start(builder):
    ReqCreateAxesPayloadStart(builder)

def ReqCreateAxesPayloadAddFigureId(builder, figureId):
    builder.PrependUint64Slot(0, figureId, 0)

def AddFigureId(builder, figureId):
    ReqCreateAxesPayloadAddFigureId(builder, figureId)

def ReqCreateAxesPayloadAddGridRows(builder, gridRows):
    builder.PrependInt32Slot(1, gridRows, 1)

def AddGridRows(builder, gridRows):
    ReqCreateAxesPayloadAddGridRows(builder, gridRows)

def ReqCreateAxesPayloadAddGridCols(builder, gridCols):
    builder.PrependInt32Slot(2, gridCols, 1)

def AddGridCols(builder, gridCols):
    ReqCreateAxesPayloadAddGridCols(builder, gridCols)

def ReqCreateAxesPayloadAddGridIndex(builder, gridIndex):
    builder.PrependInt32Slot(3, gridIndex, 1)

def AddGridIndex(builder, gridIndex):
    ReqCreateAxesPayloadAddGridIndex(builder, gridIndex)

def ReqCreateAxesPayloadAddIs3d(builder, is3d):
    builder.PrependBoolSlot(4, is3d, 0)

def AddIs3d(builder, is3d):
    ReqCreateAxesPayloadAddIs3d(builder, is3d)

def ReqCreateAxesPayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return ReqCreateAxesPayloadEnd(builder)
