# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ReqCreateWindowPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReqCreateWindowPayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReqCreateWindowPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ReqCreateWindowPayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ReqCreateWindowPayload
    def TemplateWindowId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def ReqCreateWindowPayloadStart(builder):
    builder.StartObject(1)

def Start(builder):
    ReqCreateWindowPayloadStart(builder)

def ReqCreateWindowPayloadAddTemplateWindowId(builder, templateWindowId):
    builder.PrependUint64Slot(0, templateWindowId, 0)

def AddTemplateWindowId(builder, templateWindowId):
    ReqCreateWindowPayloadAddTemplateWindowId(builder, templateWindowId)

def ReqCreateWindowPayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return ReqCreateWindowPayloadEnd(builder)
