# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ReqCreateFigurePayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReqCreateFigurePayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReqCreateFigurePayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ReqCreateFigurePayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ReqCreateFigurePayload
    def Title(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ReqCreateFigurePayload
    def Width(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 1280

    # ReqCreateFigurePayload
    def Height(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 720

def ReqCreateFigurePayloadStart(builder):
    builder.StartObject(3)

def Start(builder):
    ReqCreateFigurePayloadStart(builder)

def ReqCreateFigurePayloadAddTitle(builder, title):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(title), 0)

def AddTitle(builder, title):
    ReqCreateFigurePayloadAddTitle(builder, title)

def ReqCreateFigurePayloadAddWidth(builder, width):
    builder.PrependUint32Slot(1, width, 1280)

def AddWidth(builder, width):
    ReqCreateFigurePayloadAddWidth(builder, width)

def ReqCreateFigurePayloadAddHeight(builder, height):
    builder.PrependUint32Slot(2, height, 720)

def AddHeight(builder, height):
    ReqCreateFigurePayloadAddHeight(builder, height)

def ReqCreateFigurePayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return ReqCreateFigurePayloadEnd(builder)
