# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ReqCloseWindowPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReqCloseWindowPayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReqCloseWindowPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ReqCloseWindowPayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ReqCloseWindowPayload
    def WindowId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ReqCloseWindowPayload
    def Reason(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ReqCloseWindowPayloadStart(builder):
    builder.StartObject(2)

def Start(builder):
    ReqCloseWindowPayloadStart(builder)

def ReqCloseWindowPayloadAddWindowId(builder, windowId):
    builder.PrependUint64Slot(0, windowId, 0)

def AddWindowId(builder, windowId):
    ReqCloseWindowPayloadAddWindowId(builder, windowId)

def ReqCloseWindowPayloadAddReason(builder, reason):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(reason), 0)

def AddReason(builder, reason):
    ReqCloseWindowPayloadAddReason(builder, reason)

def ReqCloseWindowPayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return ReqCloseWindowPayloadEnd(builder)
