# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ReqCloseFigurePayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReqCloseFigurePayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReqCloseFigurePayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ReqCloseFigurePayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ReqCloseFigurePayload
    def FigureId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def ReqCloseFigurePayloadStart(builder):
    builder.StartObject(1)

def Start(builder):
    ReqCloseFigurePayloadStart(builder)

def ReqCloseFigurePayloadAddFigureId(builder, figureId):
    builder.PrependUint64Slot(0, figureId, 0)

def AddFigureId(builder, figureId):
    ReqCloseFigurePayloadAddFigureId(builder, figureId)

def ReqCloseFigurePayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return ReqCloseFigurePayloadEnd(builder)
