# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ReqDeclareTopicPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReqDeclareTopicPayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReqDeclareTopicPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ReqDeclareTopicPayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ReqDeclareTopicPayload
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ReqDeclareTopicPayload
    def Kind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ReqDeclareTopicPayload
    def Unit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ReqDeclareTopicPayload
    def RingCapacity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 4096

def ReqDeclareTopicPayloadStart(builder):
    builder.StartObject(4)

def Start(builder):
    ReqDeclareTopicPayloadStart(builder)

def ReqDeclareTopicPayloadAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    ReqDeclareTopicPayloadAddName(builder, name)

def ReqDeclareTopicPayloadAddKind(builder, kind):
    builder.PrependUint8Slot(1, kind, 0)

def AddKind(builder, kind):
    ReqDeclareTopicPayloadAddKind(builder, kind)

def ReqDeclareTopicPayloadAddUnit(builder, unit):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(unit), 0)

def AddUnit(builder, unit):
    ReqDeclareTopicPayloadAddUnit(builder, unit)

def ReqDeclareTopicPayloadAddRingCapacity(builder, ringCapacity):
    builder.PrependUint32Slot(3, ringCapacity, 4096)

def AddRingCapacity(builder, ringCapacity):
    ReqDeclareTopicPayloadAddRingCapacity(builder, ringCapacity)

def ReqDeclareTopicPayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return ReqDeclareTopicPayloadEnd(builder)
