# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ReqDestroyFigurePayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReqDestroyFigurePayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReqDestroyFigurePayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ReqDestroyFigurePayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ReqDestroyFigurePayload
    def FigureId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def ReqDestroyFigurePayloadStart(builder):
    builder.StartObject(1)

def Start(builder):
    ReqDestroyFigurePayloadStart(builder)

def ReqDestroyFigurePayloadAddFigureId(builder, figureId):
    builder.PrependUint64Slot(0, figureId, 0)

def AddFigureId(builder, figureId):
    ReqDestroyFigurePayloadAddFigureId(builder, figureId)

def ReqDestroyFigurePayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return ReqDestroyFigurePayloadEnd(builder)
