# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ReqDetachFigurePayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReqDetachFigurePayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReqDetachFigurePayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ReqDetachFigurePayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ReqDetachFigurePayload
    def SourceWindowId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ReqDetachFigurePayload
    def FigureId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ReqDetachFigurePayload
    def Width(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 800

    # ReqDetachFigurePayload
    def Height(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 600

    # ReqDetachFigurePayload
    def ScreenX(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ReqDetachFigurePayload
    def ScreenY(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def ReqDetachFigurePayloadStart(builder):
    builder.StartObject(6)

def Start(builder):
    ReqDetachFigurePayloadStart(builder)

def ReqDetachFigurePayloadAddSourceWindowId(builder, sourceWindowId):
    builder.PrependUint64Slot(0, sourceWindowId, 0)

def AddSourceWindowId(builder, sourceWindowId):
    ReqDetachFigurePayloadAddSourceWindowId(builder, sourceWindowId)

def ReqDetachFigurePayloadAddFigureId(builder, figureId):
    builder.PrependUint64Slot(1, figureId, 0)

def AddFigureId(builder, figureId):
    ReqDetachFigurePayloadAddFigureId(builder, figureId)

def ReqDetachFigurePayloadAddWidth(builder, width):
    builder.PrependUint32Slot(2, width, 800)

def AddWidth(builder, width):
    ReqDetachFigurePayloadAddWidth(builder, width)

def ReqDetachFigurePayloadAddHeight(builder, height):
    builder.PrependUint32Slot(3, height, 600)

def AddHeight(builder, height):
    ReqDetachFigurePayloadAddHeight(builder, height)

def ReqDetachFigurePayloadAddScreenX(builder, screenX):
    builder.PrependInt32Slot(4, screenX, 0)

def AddScreenX(builder, screenX):
    ReqDetachFigurePayloadAddScreenX(builder, screenX)

def ReqDetachFigurePayloadAddScreenY(builder, screenY):
    builder.PrependInt32Slot(5, screenY, 0)

def AddScreenY(builder, screenY):
    ReqDetachFigurePayloadAddScreenY(builder, screenY)

def ReqDetachFigurePayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return ReqDetachFigurePayloadEnd(builder)
