# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ReqListTopicsPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReqListTopicsPayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReqListTopicsPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ReqListTopicsPayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ReqListTopicsPayload
    def Placeholder(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def ReqListTopicsPayloadStart(builder):
    builder.StartObject(1)

def Start(builder):
    ReqListTopicsPayloadStart(builder)

def ReqListTopicsPayloadAddPlaceholder(builder, placeholder):
    builder.PrependUint8Slot(0, placeholder, 0)

def AddPlaceholder(builder, placeholder):
    ReqListTopicsPayloadAddPlaceholder(builder, placeholder)

def ReqListTopicsPayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return ReqListTopicsPayloadEnd(builder)
