# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ReqPublishTopicSamplesPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReqPublishTopicSamplesPayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReqPublishTopicSamplesPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ReqPublishTopicSamplesPayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ReqPublishTopicSamplesPayload
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ReqPublishTopicSamplesPayload
    def Samples(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # ReqPublishTopicSamplesPayload
    def SamplesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # ReqPublishTopicSamplesPayload
    def SamplesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ReqPublishTopicSamplesPayload
    def SamplesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def ReqPublishTopicSamplesPayloadStart(builder):
    builder.StartObject(2)

def Start(builder):
    ReqPublishTopicSamplesPayloadStart(builder)

def ReqPublishTopicSamplesPayloadAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    ReqPublishTopicSamplesPayloadAddName(builder, name)

def ReqPublishTopicSamplesPayloadAddSamples(builder, samples):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(samples), 0)

def AddSamples(builder, samples):
    ReqPublishTopicSamplesPayloadAddSamples(builder, samples)

def ReqPublishTopicSamplesPayloadStartSamplesVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartSamplesVector(builder, numElems):
    return ReqPublishTopicSamplesPayloadStartSamplesVector(builder, numElems)

def ReqPublishTopicSamplesPayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return ReqPublishTopicSamplesPayloadEnd(builder)
