# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ReqRemoveSeriesPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReqRemoveSeriesPayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReqRemoveSeriesPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ReqRemoveSeriesPayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ReqRemoveSeriesPayload
    def FigureId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ReqRemoveSeriesPayload
    def SeriesIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def ReqRemoveSeriesPayloadStart(builder):
    builder.StartObject(2)

def Start(builder):
    ReqRemoveSeriesPayloadStart(builder)

def ReqRemoveSeriesPayloadAddFigureId(builder, figureId):
    builder.PrependUint64Slot(0, figureId, 0)

def AddFigureId(builder, figureId):
    ReqRemoveSeriesPayloadAddFigureId(builder, figureId)

def ReqRemoveSeriesPayloadAddSeriesIndex(builder, seriesIndex):
    builder.PrependUint32Slot(1, seriesIndex, 0)

def AddSeriesIndex(builder, seriesIndex):
    ReqRemoveSeriesPayloadAddSeriesIndex(builder, seriesIndex)

def ReqRemoveSeriesPayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return ReqRemoveSeriesPayloadEnd(builder)
