# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ReqReconnectPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReqReconnectPayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReqReconnectPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ReqReconnectPayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ReqReconnectPayload
    def SessionId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ReqReconnectPayload
    def SessionToken(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ReqReconnectPayloadStart(builder):
    builder.StartObject(2)

def Start(builder):
    ReqReconnectPayloadStart(builder)

def ReqReconnectPayloadAddSessionId(builder, sessionId):
    builder.PrependUint64Slot(0, sessionId, 0)

def AddSessionId(builder, sessionId):
    ReqReconnectPayloadAddSessionId(builder, sessionId)

def ReqReconnectPayloadAddSessionToken(builder, sessionToken):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(sessionToken), 0)

def AddSessionToken(builder, sessionToken):
    ReqReconnectPayloadAddSessionToken(builder, sessionToken)

def ReqReconnectPayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return ReqReconnectPayloadEnd(builder)
