# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ReqSubscribeTopicPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReqSubscribeTopicPayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReqSubscribeTopicPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ReqSubscribeTopicPayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ReqSubscribeTopicPayload
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ReqSubscribeTopicPayload
    def FigureId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ReqSubscribeTopicPayload
    def AxesIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ReqSubscribeTopicPayload
    def SeriesIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 4294967295

def ReqSubscribeTopicPayloadStart(builder):
    builder.StartObject(4)

def Start(builder):
    ReqSubscribeTopicPayloadStart(builder)

def ReqSubscribeTopicPayloadAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    ReqSubscribeTopicPayloadAddName(builder, name)

def ReqSubscribeTopicPayloadAddFigureId(builder, figureId):
    builder.PrependUint64Slot(1, figureId, 0)

def AddFigureId(builder, figureId):
    ReqSubscribeTopicPayloadAddFigureId(builder, figureId)

def ReqSubscribeTopicPayloadAddAxesIndex(builder, axesIndex):
    builder.PrependUint32Slot(2, axesIndex, 0)

def AddAxesIndex(builder, axesIndex):
    ReqSubscribeTopicPayloadAddAxesIndex(builder, axesIndex)

def ReqSubscribeTopicPayloadAddSeriesIndex(builder, seriesIndex):
    builder.PrependUint32Slot(3, seriesIndex, 4294967295)

def AddSeriesIndex(builder, seriesIndex):
    ReqSubscribeTopicPayloadAddSeriesIndex(builder, seriesIndex)

def ReqSubscribeTopicPayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return ReqSubscribeTopicPayloadEnd(builder)
