# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ReqSetDataPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReqSetDataPayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReqSetDataPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ReqSetDataPayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ReqSetDataPayload
    def FigureId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ReqSetDataPayload
    def SeriesIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ReqSetDataPayload
    def Dtype(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ReqSetDataPayload
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # ReqSetDataPayload
    def DataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # ReqSetDataPayload
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ReqSetDataPayload
    def DataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def ReqSetDataPayloadStart(builder):
    builder.StartObject(4)

def Start(builder):
    ReqSetDataPayloadStart(builder)

def ReqSetDataPayloadAddFigureId(builder, figureId):
    builder.PrependUint64Slot(0, figureId, 0)

def AddFigureId(builder, figureId):
    ReqSetDataPayloadAddFigureId(builder, figureId)

def ReqSetDataPayloadAddSeriesIndex(builder, seriesIndex):
    builder.PrependUint32Slot(1, seriesIndex, 0)

def AddSeriesIndex(builder, seriesIndex):
    ReqSetDataPayloadAddSeriesIndex(builder, seriesIndex)

def ReqSetDataPayloadAddDtype(builder, dtype):
    builder.PrependUint8Slot(2, dtype, 0)

def AddDtype(builder, dtype):
    ReqSetDataPayloadAddDtype(builder, dtype)

def ReqSetDataPayloadAddData(builder, data):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)

def AddData(builder, data):
    ReqSetDataPayloadAddData(builder, data)

def ReqSetDataPayloadStartDataVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartDataVector(builder, numElems):
    return ReqSetDataPayloadStartDataVector(builder, numElems)

def ReqSetDataPayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return ReqSetDataPayloadEnd(builder)
