# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ReqUnsubscribeTopicPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReqUnsubscribeTopicPayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReqUnsubscribeTopicPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ReqUnsubscribeTopicPayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ReqUnsubscribeTopicPayload
    def FigureId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ReqUnsubscribeTopicPayload
    def AxesIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ReqUnsubscribeTopicPayload
    def SeriesIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def ReqUnsubscribeTopicPayloadStart(builder):
    builder.StartObject(3)

def Start(builder):
    ReqUnsubscribeTopicPayloadStart(builder)

def ReqUnsubscribeTopicPayloadAddFigureId(builder, figureId):
    builder.PrependUint64Slot(0, figureId, 0)

def AddFigureId(builder, figureId):
    ReqUnsubscribeTopicPayloadAddFigureId(builder, figureId)

def ReqUnsubscribeTopicPayloadAddAxesIndex(builder, axesIndex):
    builder.PrependUint32Slot(1, axesIndex, 0)

def AddAxesIndex(builder, axesIndex):
    ReqUnsubscribeTopicPayloadAddAxesIndex(builder, axesIndex)

def ReqUnsubscribeTopicPayloadAddSeriesIndex(builder, seriesIndex):
    builder.PrependUint32Slot(2, seriesIndex, 0)

def AddSeriesIndex(builder, seriesIndex):
    ReqUnsubscribeTopicPayloadAddSeriesIndex(builder, seriesIndex)

def ReqUnsubscribeTopicPayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return ReqUnsubscribeTopicPayloadEnd(builder)
