# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ReqUpdateBatchPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReqUpdateBatchPayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReqUpdateBatchPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ReqUpdateBatchPayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ReqUpdateBatchPayload
    def Updates(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from spectra.ipc.fb.ReqUpdatePropertyPayload import ReqUpdatePropertyPayload
            obj = ReqUpdatePropertyPayload()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ReqUpdateBatchPayload
    def UpdatesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ReqUpdateBatchPayload
    def UpdatesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def ReqUpdateBatchPayloadStart(builder):
    builder.StartObject(1)

def Start(builder):
    ReqUpdateBatchPayloadStart(builder)

def ReqUpdateBatchPayloadAddUpdates(builder, updates):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(updates), 0)

def AddUpdates(builder, updates):
    ReqUpdateBatchPayloadAddUpdates(builder, updates)

def ReqUpdateBatchPayloadStartUpdatesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartUpdatesVector(builder, numElems):
    return ReqUpdateBatchPayloadStartUpdatesVector(builder, numElems)

def ReqUpdateBatchPayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return ReqUpdateBatchPayloadEnd(builder)
