# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ReqUpdatePropertyPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReqUpdatePropertyPayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReqUpdatePropertyPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ReqUpdatePropertyPayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ReqUpdatePropertyPayload
    def FigureId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ReqUpdatePropertyPayload
    def AxesIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ReqUpdatePropertyPayload
    def SeriesIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ReqUpdatePropertyPayload
    def Property(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ReqUpdatePropertyPayload
    def F1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # ReqUpdatePropertyPayload
    def F2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # ReqUpdatePropertyPayload
    def F3(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # ReqUpdatePropertyPayload
    def F4(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # ReqUpdatePropertyPayload
    def BoolVal(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ReqUpdatePropertyPayload
    def StrVal(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ReqUpdatePropertyPayloadStart(builder):
    builder.StartObject(10)

def Start(builder):
    ReqUpdatePropertyPayloadStart(builder)

def ReqUpdatePropertyPayloadAddFigureId(builder, figureId):
    builder.PrependUint64Slot(0, figureId, 0)

def AddFigureId(builder, figureId):
    ReqUpdatePropertyPayloadAddFigureId(builder, figureId)

def ReqUpdatePropertyPayloadAddAxesIndex(builder, axesIndex):
    builder.PrependUint32Slot(1, axesIndex, 0)

def AddAxesIndex(builder, axesIndex):
    ReqUpdatePropertyPayloadAddAxesIndex(builder, axesIndex)

def ReqUpdatePropertyPayloadAddSeriesIndex(builder, seriesIndex):
    builder.PrependUint32Slot(2, seriesIndex, 0)

def AddSeriesIndex(builder, seriesIndex):
    ReqUpdatePropertyPayloadAddSeriesIndex(builder, seriesIndex)

def ReqUpdatePropertyPayloadAddProperty(builder, property):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(property), 0)

def AddProperty(builder, property):
    ReqUpdatePropertyPayloadAddProperty(builder, property)

def ReqUpdatePropertyPayloadAddF1(builder, f1):
    builder.PrependFloat64Slot(4, f1, 0.0)

def AddF1(builder, f1):
    ReqUpdatePropertyPayloadAddF1(builder, f1)

def ReqUpdatePropertyPayloadAddF2(builder, f2):
    builder.PrependFloat64Slot(5, f2, 0.0)

def AddF2(builder, f2):
    ReqUpdatePropertyPayloadAddF2(builder, f2)

def ReqUpdatePropertyPayloadAddF3(builder, f3):
    builder.PrependFloat64Slot(6, f3, 0.0)

def AddF3(builder, f3):
    ReqUpdatePropertyPayloadAddF3(builder, f3)

def ReqUpdatePropertyPayloadAddF4(builder, f4):
    builder.PrependFloat64Slot(7, f4, 0.0)

def AddF4(builder, f4):
    ReqUpdatePropertyPayloadAddF4(builder, f4)

def ReqUpdatePropertyPayloadAddBoolVal(builder, boolVal):
    builder.PrependBoolSlot(8, boolVal, 0)

def AddBoolVal(builder, boolVal):
    ReqUpdatePropertyPayloadAddBoolVal(builder, boolVal)

def ReqUpdatePropertyPayloadAddStrVal(builder, strVal):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(strVal), 0)

def AddStrVal(builder, strVal):
    ReqUpdatePropertyPayloadAddStrVal(builder, strVal)

def ReqUpdatePropertyPayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return ReqUpdatePropertyPayloadEnd(builder)
