# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RespOkPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RespOkPayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRespOkPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RespOkPayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RespOkPayload
    def RequestId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def RespOkPayloadStart(builder):
    builder.StartObject(1)

def Start(builder):
    RespOkPayloadStart(builder)

def RespOkPayloadAddRequestId(builder, requestId):
    builder.PrependUint64Slot(0, requestId, 0)

def AddRequestId(builder, requestId):
    RespOkPayloadAddRequestId(builder, requestId)

def RespOkPayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return RespOkPayloadEnd(builder)
