# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RespFigureListPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RespFigureListPayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRespFigureListPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RespFigureListPayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RespFigureListPayload
    def RequestId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # RespFigureListPayload
    def FigureIds(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # RespFigureListPayload
    def FigureIdsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint64Flags, o)
        return 0

    # RespFigureListPayload
    def FigureIdsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RespFigureListPayload
    def FigureIdsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def RespFigureListPayloadStart(builder):
    builder.StartObject(2)

def Start(builder):
    RespFigureListPayloadStart(builder)

def RespFigureListPayloadAddRequestId(builder, requestId):
    builder.PrependUint64Slot(0, requestId, 0)

def AddRequestId(builder, requestId):
    RespFigureListPayloadAddRequestId(builder, requestId)

def RespFigureListPayloadAddFigureIds(builder, figureIds):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(figureIds), 0)

def AddFigureIds(builder, figureIds):
    RespFigureListPayloadAddFigureIds(builder, figureIds)

def RespFigureListPayloadStartFigureIdsVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartFigureIdsVector(builder, numElems):
    return RespFigureListPayloadStartFigureIdsVector(builder, numElems)

def RespFigureListPayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return RespFigureListPayloadEnd(builder)
