# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RespTopicListPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RespTopicListPayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRespTopicListPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RespTopicListPayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RespTopicListPayload
    def RequestId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # RespTopicListPayload
    def Topics(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from spectra.ipc.fb.TopicInfoEntry import TopicInfoEntry
            obj = TopicInfoEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RespTopicListPayload
    def TopicsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RespTopicListPayload
    def TopicsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def RespTopicListPayloadStart(builder):
    builder.StartObject(2)

def Start(builder):
    RespTopicListPayloadStart(builder)

def RespTopicListPayloadAddRequestId(builder, requestId):
    builder.PrependUint64Slot(0, requestId, 0)

def AddRequestId(builder, requestId):
    RespTopicListPayloadAddRequestId(builder, requestId)

def RespTopicListPayloadAddTopics(builder, topics):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(topics), 0)

def AddTopics(builder, topics):
    RespTopicListPayloadAddTopics(builder, topics)

def RespTopicListPayloadStartTopicsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTopicsVector(builder, numElems):
    return RespTopicListPayloadStartTopicsVector(builder, numElems)

def RespTopicListPayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return RespTopicListPayloadEnd(builder)
