# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RespErrPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RespErrPayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRespErrPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RespErrPayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RespErrPayload
    def RequestId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # RespErrPayload
    def Code(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # RespErrPayload
    def Message(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def RespErrPayloadStart(builder):
    builder.StartObject(3)

def Start(builder):
    RespErrPayloadStart(builder)

def RespErrPayloadAddRequestId(builder, requestId):
    builder.PrependUint64Slot(0, requestId, 0)

def AddRequestId(builder, requestId):
    RespErrPayloadAddRequestId(builder, requestId)

def RespErrPayloadAddCode(builder, code):
    builder.PrependUint32Slot(1, code, 0)

def AddCode(builder, code):
    RespErrPayloadAddCode(builder, code)

def RespErrPayloadAddMessage(builder, message):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def AddMessage(builder, message):
    RespErrPayloadAddMessage(builder, message)

def RespErrPayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return RespErrPayloadEnd(builder)
