# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RespAxesCreatedPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RespAxesCreatedPayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRespAxesCreatedPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RespAxesCreatedPayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RespAxesCreatedPayload
    def RequestId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # RespAxesCreatedPayload
    def AxesIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def RespAxesCreatedPayloadStart(builder):
    builder.StartObject(2)

def Start(builder):
    RespAxesCreatedPayloadStart(builder)

def RespAxesCreatedPayloadAddRequestId(builder, requestId):
    builder.PrependUint64Slot(0, requestId, 0)

def AddRequestId(builder, requestId):
    RespAxesCreatedPayloadAddRequestId(builder, requestId)

def RespAxesCreatedPayloadAddAxesIndex(builder, axesIndex):
    builder.PrependUint32Slot(1, axesIndex, 0)

def AddAxesIndex(builder, axesIndex):
    RespAxesCreatedPayloadAddAxesIndex(builder, axesIndex)

def RespAxesCreatedPayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return RespAxesCreatedPayloadEnd(builder)
