# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RespFigureCreatedPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RespFigureCreatedPayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRespFigureCreatedPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RespFigureCreatedPayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RespFigureCreatedPayload
    def RequestId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # RespFigureCreatedPayload
    def FigureId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def RespFigureCreatedPayloadStart(builder):
    builder.StartObject(2)

def Start(builder):
    RespFigureCreatedPayloadStart(builder)

def RespFigureCreatedPayloadAddRequestId(builder, requestId):
    builder.PrependUint64Slot(0, requestId, 0)

def AddRequestId(builder, requestId):
    RespFigureCreatedPayloadAddRequestId(builder, requestId)

def RespFigureCreatedPayloadAddFigureId(builder, figureId):
    builder.PrependUint64Slot(1, figureId, 0)

def AddFigureId(builder, figureId):
    RespFigureCreatedPayloadAddFigureId(builder, figureId)

def RespFigureCreatedPayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return RespFigureCreatedPayloadEnd(builder)
