# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RespSeriesAddedPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RespSeriesAddedPayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRespSeriesAddedPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RespSeriesAddedPayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RespSeriesAddedPayload
    def RequestId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # RespSeriesAddedPayload
    def SeriesIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def RespSeriesAddedPayloadStart(builder):
    builder.StartObject(2)

def Start(builder):
    RespSeriesAddedPayloadStart(builder)

def RespSeriesAddedPayloadAddRequestId(builder, requestId):
    builder.PrependUint64Slot(0, requestId, 0)

def AddRequestId(builder, requestId):
    RespSeriesAddedPayloadAddRequestId(builder, requestId)

def RespSeriesAddedPayloadAddSeriesIndex(builder, seriesIndex):
    builder.PrependUint32Slot(1, seriesIndex, 0)

def AddSeriesIndex(builder, seriesIndex):
    RespSeriesAddedPayloadAddSeriesIndex(builder, seriesIndex)

def RespSeriesAddedPayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return RespSeriesAddedPayloadEnd(builder)
