# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SnapshotKnobState(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SnapshotKnobState()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSnapshotKnobState(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SnapshotKnobState
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SnapshotKnobState
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SnapshotKnobState
    def KnobType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # SnapshotKnobState
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # SnapshotKnobState
    def MinVal(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # SnapshotKnobState
    def MaxVal(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 1.0

    # SnapshotKnobState
    def Step(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # SnapshotKnobState
    def Choices(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # SnapshotKnobState
    def ChoicesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SnapshotKnobState
    def ChoicesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

def SnapshotKnobStateStart(builder):
    builder.StartObject(7)

def Start(builder):
    SnapshotKnobStateStart(builder)

def SnapshotKnobStateAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    SnapshotKnobStateAddName(builder, name)

def SnapshotKnobStateAddKnobType(builder, knobType):
    builder.PrependUint8Slot(1, knobType, 0)

def AddKnobType(builder, knobType):
    SnapshotKnobStateAddKnobType(builder, knobType)

def SnapshotKnobStateAddValue(builder, value):
    builder.PrependFloat32Slot(2, value, 0.0)

def AddValue(builder, value):
    SnapshotKnobStateAddValue(builder, value)

def SnapshotKnobStateAddMinVal(builder, minVal):
    builder.PrependFloat32Slot(3, minVal, 0.0)

def AddMinVal(builder, minVal):
    SnapshotKnobStateAddMinVal(builder, minVal)

def SnapshotKnobStateAddMaxVal(builder, maxVal):
    builder.PrependFloat32Slot(4, maxVal, 1.0)

def AddMaxVal(builder, maxVal):
    SnapshotKnobStateAddMaxVal(builder, maxVal)

def SnapshotKnobStateAddStep(builder, step):
    builder.PrependFloat32Slot(5, step, 0.0)

def AddStep(builder, step):
    SnapshotKnobStateAddStep(builder, step)

def SnapshotKnobStateAddChoices(builder, choices):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(choices), 0)

def AddChoices(builder, choices):
    SnapshotKnobStateAddChoices(builder, choices)

def SnapshotKnobStateStartChoicesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartChoicesVector(builder, numElems):
    return SnapshotKnobStateStartChoicesVector(builder, numElems)

def SnapshotKnobStateEnd(builder):
    return builder.EndObject()

def End(builder):
    return SnapshotKnobStateEnd(builder)
