# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SnapshotAxisState(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SnapshotAxisState()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSnapshotAxisState(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SnapshotAxisState
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SnapshotAxisState
    def XMin(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # SnapshotAxisState
    def XMax(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 1.0

    # SnapshotAxisState
    def YMin(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # SnapshotAxisState
    def YMax(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 1.0

    # SnapshotAxisState
    def ZMin(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # SnapshotAxisState
    def ZMax(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 1.0

    # SnapshotAxisState
    def GridVisible(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

    # SnapshotAxisState
    def Is3d(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # SnapshotAxisState
    def XLabel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SnapshotAxisState
    def YLabel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SnapshotAxisState
    def Title(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def SnapshotAxisStateStart(builder):
    builder.StartObject(11)

def Start(builder):
    SnapshotAxisStateStart(builder)

def SnapshotAxisStateAddXMin(builder, xMin):
    builder.PrependFloat64Slot(0, xMin, 0.0)

def AddXMin(builder, xMin):
    SnapshotAxisStateAddXMin(builder, xMin)

def SnapshotAxisStateAddXMax(builder, xMax):
    builder.PrependFloat64Slot(1, xMax, 1.0)

def AddXMax(builder, xMax):
    SnapshotAxisStateAddXMax(builder, xMax)

def SnapshotAxisStateAddYMin(builder, yMin):
    builder.PrependFloat64Slot(2, yMin, 0.0)

def AddYMin(builder, yMin):
    SnapshotAxisStateAddYMin(builder, yMin)

def SnapshotAxisStateAddYMax(builder, yMax):
    builder.PrependFloat64Slot(3, yMax, 1.0)

def AddYMax(builder, yMax):
    SnapshotAxisStateAddYMax(builder, yMax)

def SnapshotAxisStateAddZMin(builder, zMin):
    builder.PrependFloat64Slot(4, zMin, 0.0)

def AddZMin(builder, zMin):
    SnapshotAxisStateAddZMin(builder, zMin)

def SnapshotAxisStateAddZMax(builder, zMax):
    builder.PrependFloat64Slot(5, zMax, 1.0)

def AddZMax(builder, zMax):
    SnapshotAxisStateAddZMax(builder, zMax)

def SnapshotAxisStateAddGridVisible(builder, gridVisible):
    builder.PrependBoolSlot(6, gridVisible, 1)

def AddGridVisible(builder, gridVisible):
    SnapshotAxisStateAddGridVisible(builder, gridVisible)

def SnapshotAxisStateAddIs3d(builder, is3d):
    builder.PrependBoolSlot(7, is3d, 0)

def AddIs3d(builder, is3d):
    SnapshotAxisStateAddIs3d(builder, is3d)

def SnapshotAxisStateAddXLabel(builder, xLabel):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(xLabel), 0)

def AddXLabel(builder, xLabel):
    SnapshotAxisStateAddXLabel(builder, xLabel)

def SnapshotAxisStateAddYLabel(builder, yLabel):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(yLabel), 0)

def AddYLabel(builder, yLabel):
    SnapshotAxisStateAddYLabel(builder, yLabel)

def SnapshotAxisStateAddTitle(builder, title):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(title), 0)

def AddTitle(builder, title):
    SnapshotAxisStateAddTitle(builder, title)

def SnapshotAxisStateEnd(builder):
    return builder.EndObject()

def End(builder):
    return SnapshotAxisStateEnd(builder)
