# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SnapshotFigureState(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SnapshotFigureState()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSnapshotFigureState(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SnapshotFigureState
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SnapshotFigureState
    def FigureId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # SnapshotFigureState
    def Title(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SnapshotFigureState
    def Width(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 1280

    # SnapshotFigureState
    def Height(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 720

    # SnapshotFigureState
    def GridRows(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 1

    # SnapshotFigureState
    def GridCols(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 1

    # SnapshotFigureState
    def WindowGroup(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # SnapshotFigureState
    def Axes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from spectra.ipc.fb.SnapshotAxisState import SnapshotAxisState
            obj = SnapshotAxisState()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SnapshotFigureState
    def AxesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SnapshotFigureState
    def AxesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # SnapshotFigureState
    def Series(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from spectra.ipc.fb.SnapshotSeriesState import SnapshotSeriesState
            obj = SnapshotSeriesState()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SnapshotFigureState
    def SeriesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SnapshotFigureState
    def SeriesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

def SnapshotFigureStateStart(builder):
    builder.StartObject(9)

def Start(builder):
    SnapshotFigureStateStart(builder)

def SnapshotFigureStateAddFigureId(builder, figureId):
    builder.PrependUint64Slot(0, figureId, 0)

def AddFigureId(builder, figureId):
    SnapshotFigureStateAddFigureId(builder, figureId)

def SnapshotFigureStateAddTitle(builder, title):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(title), 0)

def AddTitle(builder, title):
    SnapshotFigureStateAddTitle(builder, title)

def SnapshotFigureStateAddWidth(builder, width):
    builder.PrependUint32Slot(2, width, 1280)

def AddWidth(builder, width):
    SnapshotFigureStateAddWidth(builder, width)

def SnapshotFigureStateAddHeight(builder, height):
    builder.PrependUint32Slot(3, height, 720)

def AddHeight(builder, height):
    SnapshotFigureStateAddHeight(builder, height)

def SnapshotFigureStateAddGridRows(builder, gridRows):
    builder.PrependInt32Slot(4, gridRows, 1)

def AddGridRows(builder, gridRows):
    SnapshotFigureStateAddGridRows(builder, gridRows)

def SnapshotFigureStateAddGridCols(builder, gridCols):
    builder.PrependInt32Slot(5, gridCols, 1)

def AddGridCols(builder, gridCols):
    SnapshotFigureStateAddGridCols(builder, gridCols)

def SnapshotFigureStateAddWindowGroup(builder, windowGroup):
    builder.PrependUint32Slot(6, windowGroup, 0)

def AddWindowGroup(builder, windowGroup):
    SnapshotFigureStateAddWindowGroup(builder, windowGroup)

def SnapshotFigureStateAddAxes(builder, axes):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(axes), 0)

def AddAxes(builder, axes):
    SnapshotFigureStateAddAxes(builder, axes)

def SnapshotFigureStateStartAxesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartAxesVector(builder, numElems):
    return SnapshotFigureStateStartAxesVector(builder, numElems)

def SnapshotFigureStateAddSeries(builder, series):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(series), 0)

def AddSeries(builder, series):
    SnapshotFigureStateAddSeries(builder, series)

def SnapshotFigureStateStartSeriesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSeriesVector(builder, numElems):
    return SnapshotFigureStateStartSeriesVector(builder, numElems)

def SnapshotFigureStateEnd(builder):
    return builder.EndObject()

def End(builder):
    return SnapshotFigureStateEnd(builder)
