# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SnapshotSeriesState(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SnapshotSeriesState()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSnapshotSeriesState(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SnapshotSeriesState
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SnapshotSeriesState
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SnapshotSeriesState
    def SeriesType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SnapshotSeriesState
    def ColorR(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 1.0

    # SnapshotSeriesState
    def ColorG(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 1.0

    # SnapshotSeriesState
    def ColorB(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 1.0

    # SnapshotSeriesState
    def ColorA(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 1.0

    # SnapshotSeriesState
    def LineWidth(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 2.0

    # SnapshotSeriesState
    def MarkerSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 6.0

    # SnapshotSeriesState
    def Visible(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return True

    # SnapshotSeriesState
    def Opacity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 1.0

    # SnapshotSeriesState
    def PointCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # SnapshotSeriesState
    def AxesIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # SnapshotSeriesState
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # SnapshotSeriesState
    def DataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # SnapshotSeriesState
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SnapshotSeriesState
    def DataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        return o == 0

def SnapshotSeriesStateStart(builder):
    builder.StartObject(13)

def Start(builder):
    SnapshotSeriesStateStart(builder)

def SnapshotSeriesStateAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    SnapshotSeriesStateAddName(builder, name)

def SnapshotSeriesStateAddSeriesType(builder, seriesType):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(seriesType), 0)

def AddSeriesType(builder, seriesType):
    SnapshotSeriesStateAddSeriesType(builder, seriesType)

def SnapshotSeriesStateAddColorR(builder, colorR):
    builder.PrependFloat32Slot(2, colorR, 1.0)

def AddColorR(builder, colorR):
    SnapshotSeriesStateAddColorR(builder, colorR)

def SnapshotSeriesStateAddColorG(builder, colorG):
    builder.PrependFloat32Slot(3, colorG, 1.0)

def AddColorG(builder, colorG):
    SnapshotSeriesStateAddColorG(builder, colorG)

def SnapshotSeriesStateAddColorB(builder, colorB):
    builder.PrependFloat32Slot(4, colorB, 1.0)

def AddColorB(builder, colorB):
    SnapshotSeriesStateAddColorB(builder, colorB)

def SnapshotSeriesStateAddColorA(builder, colorA):
    builder.PrependFloat32Slot(5, colorA, 1.0)

def AddColorA(builder, colorA):
    SnapshotSeriesStateAddColorA(builder, colorA)

def SnapshotSeriesStateAddLineWidth(builder, lineWidth):
    builder.PrependFloat32Slot(6, lineWidth, 2.0)

def AddLineWidth(builder, lineWidth):
    SnapshotSeriesStateAddLineWidth(builder, lineWidth)

def SnapshotSeriesStateAddMarkerSize(builder, markerSize):
    builder.PrependFloat32Slot(7, markerSize, 6.0)

def AddMarkerSize(builder, markerSize):
    SnapshotSeriesStateAddMarkerSize(builder, markerSize)

def SnapshotSeriesStateAddVisible(builder, visible):
    builder.PrependBoolSlot(8, visible, 1)

def AddVisible(builder, visible):
    SnapshotSeriesStateAddVisible(builder, visible)

def SnapshotSeriesStateAddOpacity(builder, opacity):
    builder.PrependFloat32Slot(9, opacity, 1.0)

def AddOpacity(builder, opacity):
    SnapshotSeriesStateAddOpacity(builder, opacity)

def SnapshotSeriesStateAddPointCount(builder, pointCount):
    builder.PrependUint32Slot(10, pointCount, 0)

def AddPointCount(builder, pointCount):
    SnapshotSeriesStateAddPointCount(builder, pointCount)

def SnapshotSeriesStateAddAxesIndex(builder, axesIndex):
    builder.PrependUint32Slot(11, axesIndex, 0)

def AddAxesIndex(builder, axesIndex):
    SnapshotSeriesStateAddAxesIndex(builder, axesIndex)

def SnapshotSeriesStateAddData(builder, data):
    builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)

def AddData(builder, data):
    SnapshotSeriesStateAddData(builder, data)

def SnapshotSeriesStateStartDataVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartDataVector(builder, numElems):
    return SnapshotSeriesStateStartDataVector(builder, numElems)

def SnapshotSeriesStateEnd(builder):
    return builder.EndObject()

def End(builder):
    return SnapshotSeriesStateEnd(builder)
