# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StateSnapshotPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StateSnapshotPayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStateSnapshotPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StateSnapshotPayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StateSnapshotPayload
    def Revision(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # StateSnapshotPayload
    def SessionId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # StateSnapshotPayload
    def Figures(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from spectra.ipc.fb.SnapshotFigureState import SnapshotFigureState
            obj = SnapshotFigureState()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # StateSnapshotPayload
    def FiguresLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # StateSnapshotPayload
    def FiguresIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # StateSnapshotPayload
    def Knobs(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from spectra.ipc.fb.SnapshotKnobState import SnapshotKnobState
            obj = SnapshotKnobState()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # StateSnapshotPayload
    def KnobsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # StateSnapshotPayload
    def KnobsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def StateSnapshotPayloadStart(builder):
    builder.StartObject(4)

def Start(builder):
    StateSnapshotPayloadStart(builder)

def StateSnapshotPayloadAddRevision(builder, revision):
    builder.PrependUint64Slot(0, revision, 0)

def AddRevision(builder, revision):
    StateSnapshotPayloadAddRevision(builder, revision)

def StateSnapshotPayloadAddSessionId(builder, sessionId):
    builder.PrependUint64Slot(1, sessionId, 0)

def AddSessionId(builder, sessionId):
    StateSnapshotPayloadAddSessionId(builder, sessionId)

def StateSnapshotPayloadAddFigures(builder, figures):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(figures), 0)

def AddFigures(builder, figures):
    StateSnapshotPayloadAddFigures(builder, figures)

def StateSnapshotPayloadStartFiguresVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartFiguresVector(builder, numElems):
    return StateSnapshotPayloadStartFiguresVector(builder, numElems)

def StateSnapshotPayloadAddKnobs(builder, knobs):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(knobs), 0)

def AddKnobs(builder, knobs):
    StateSnapshotPayloadAddKnobs(builder, knobs)

def StateSnapshotPayloadStartKnobsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartKnobsVector(builder, numElems):
    return StateSnapshotPayloadStartKnobsVector(builder, numElems)

def StateSnapshotPayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return StateSnapshotPayloadEnd(builder)
