# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StateDiffPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StateDiffPayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStateDiffPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StateDiffPayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StateDiffPayload
    def BaseRevision(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # StateDiffPayload
    def NewRevision(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # StateDiffPayload
    def Ops(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from spectra.ipc.fb.DiffOp import DiffOp
            obj = DiffOp()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # StateDiffPayload
    def OpsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # StateDiffPayload
    def OpsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def StateDiffPayloadStart(builder):
    builder.StartObject(3)

def Start(builder):
    StateDiffPayloadStart(builder)

def StateDiffPayloadAddBaseRevision(builder, baseRevision):
    builder.PrependUint64Slot(0, baseRevision, 0)

def AddBaseRevision(builder, baseRevision):
    StateDiffPayloadAddBaseRevision(builder, baseRevision)

def StateDiffPayloadAddNewRevision(builder, newRevision):
    builder.PrependUint64Slot(1, newRevision, 0)

def AddNewRevision(builder, newRevision):
    StateDiffPayloadAddNewRevision(builder, newRevision)

def StateDiffPayloadAddOps(builder, ops):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(ops), 0)

def AddOps(builder, ops):
    StateDiffPayloadAddOps(builder, ops)

def StateDiffPayloadStartOpsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartOpsVector(builder, numElems):
    return StateDiffPayloadStartOpsVector(builder, numElems)

def StateDiffPayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return StateDiffPayloadEnd(builder)
