# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TopicInfoEntry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TopicInfoEntry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTopicInfoEntry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TopicInfoEntry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TopicInfoEntry
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TopicInfoEntry
    def Kind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # TopicInfoEntry
    def Unit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TopicInfoEntry
    def EstimatedHz(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # TopicInfoEntry
    def TotalSamples(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # TopicInfoEntry
    def LastPublishNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # TopicInfoEntry
    def SubscriberCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # TopicInfoEntry
    def PublisherOnline(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def TopicInfoEntryStart(builder):
    builder.StartObject(8)

def Start(builder):
    TopicInfoEntryStart(builder)

def TopicInfoEntryAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    TopicInfoEntryAddName(builder, name)

def TopicInfoEntryAddKind(builder, kind):
    builder.PrependUint8Slot(1, kind, 0)

def AddKind(builder, kind):
    TopicInfoEntryAddKind(builder, kind)

def TopicInfoEntryAddUnit(builder, unit):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(unit), 0)

def AddUnit(builder, unit):
    TopicInfoEntryAddUnit(builder, unit)

def TopicInfoEntryAddEstimatedHz(builder, estimatedHz):
    builder.PrependFloat64Slot(3, estimatedHz, 0.0)

def AddEstimatedHz(builder, estimatedHz):
    TopicInfoEntryAddEstimatedHz(builder, estimatedHz)

def TopicInfoEntryAddTotalSamples(builder, totalSamples):
    builder.PrependUint64Slot(4, totalSamples, 0)

def AddTotalSamples(builder, totalSamples):
    TopicInfoEntryAddTotalSamples(builder, totalSamples)

def TopicInfoEntryAddLastPublishNs(builder, lastPublishNs):
    builder.PrependUint64Slot(5, lastPublishNs, 0)

def AddLastPublishNs(builder, lastPublishNs):
    TopicInfoEntryAddLastPublishNs(builder, lastPublishNs)

def TopicInfoEntryAddSubscriberCount(builder, subscriberCount):
    builder.PrependUint32Slot(6, subscriberCount, 0)

def AddSubscriberCount(builder, subscriberCount):
    TopicInfoEntryAddSubscriberCount(builder, subscriberCount)

def TopicInfoEntryAddPublisherOnline(builder, publisherOnline):
    builder.PrependBoolSlot(7, publisherOnline, 0)

def AddPublisherOnline(builder, publisherOnline):
    TopicInfoEntryAddPublisherOnline(builder, publisherOnline)

def TopicInfoEntryEnd(builder):
    return builder.EndObject()

def End(builder):
    return TopicInfoEntryEnd(builder)
