# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WelcomePayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WelcomePayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWelcomePayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WelcomePayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WelcomePayload
    def SessionId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # WelcomePayload
    def WindowId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # WelcomePayload
    def ProcessId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # WelcomePayload
    def HeartbeatMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 5000

    # WelcomePayload
    def Mode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def WelcomePayloadStart(builder):
    builder.StartObject(5)

def Start(builder):
    WelcomePayloadStart(builder)

def WelcomePayloadAddSessionId(builder, sessionId):
    builder.PrependUint64Slot(0, sessionId, 0)

def AddSessionId(builder, sessionId):
    WelcomePayloadAddSessionId(builder, sessionId)

def WelcomePayloadAddWindowId(builder, windowId):
    builder.PrependUint64Slot(1, windowId, 0)

def AddWindowId(builder, windowId):
    WelcomePayloadAddWindowId(builder, windowId)

def WelcomePayloadAddProcessId(builder, processId):
    builder.PrependUint64Slot(2, processId, 0)

def AddProcessId(builder, processId):
    WelcomePayloadAddProcessId(builder, processId)

def WelcomePayloadAddHeartbeatMs(builder, heartbeatMs):
    builder.PrependUint32Slot(3, heartbeatMs, 5000)

def AddHeartbeatMs(builder, heartbeatMs):
    WelcomePayloadAddHeartbeatMs(builder, heartbeatMs)

def WelcomePayloadAddMode(builder, mode):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(mode), 0)

def AddMode(builder, mode):
    WelcomePayloadAddMode(builder, mode)

def WelcomePayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return WelcomePayloadEnd(builder)
