# EmbedWGSLShaders.cmake
# Reads each .wgsl source file listed in WGSL_SOURCES and generates a single
# C++ header (WGSL_HEADER) containing one constexpr const char* per shader.
#
# Variable name convention: a file named "line.wgsl" becomes
#   wgsl::line_wgsl  (const char*)

cmake_minimum_required(VERSION 3.20)

# Called in script mode (-P) with:
#   -DWGSL_SOURCE_DIR=<dir>
#   -DOUTPUT_HEADER=<path>

if(NOT DEFINED WGSL_SOURCE_DIR)
    message(FATAL_ERROR "EmbedWGSLShaders: WGSL_SOURCE_DIR not set")
endif()
if(NOT DEFINED OUTPUT_HEADER)
    message(FATAL_ERROR "EmbedWGSLShaders: OUTPUT_HEADER not set")
endif()

file(GLOB WGSL_FILES "${WGSL_SOURCE_DIR}/*.wgsl")

set(_out "// Auto-generated by cmake/EmbedWGSLShaders.cmake — do not edit.\n")
string(APPEND _out "#pragma once\n\n")
string(APPEND _out "namespace spectra::wgsl\n{\n\n")

foreach(_f ${WGSL_FILES})
    get_filename_component(_name ${_f} NAME_WE)
    # Read raw bytes and hex-encode them so the string is self-contained.
    file(READ ${_f} _raw_content)
    # Escape backslashes, double-quotes, and special characters.
    string(REPLACE "\\" "\\\\" _raw_content "${_raw_content}")
    string(REPLACE "\"" "\\\"" _raw_content "${_raw_content}")
    string(REPLACE "\n" "\\n\"\n\"" _raw_content "${_raw_content}")
    string(APPEND _out "// WGSL source: ${_name}.wgsl\n")
    string(APPEND _out "inline constexpr const char* ${_name}_wgsl =\n")
    string(APPEND _out "\"${_raw_content}\";\n\n")
endforeach()

string(APPEND _out "}  // namespace spectra::wgsl\n")

file(WRITE ${OUTPUT_HEADER} "${_out}")
message(STATUS "Generated WGSL shader header: ${OUTPUT_HEADER}")
